# Generated by Django 3.2 on 2022-06-06 17:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imhotep_SedesReportes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codreg_sede', models.CharField(default='', max_length=30)),
                ('nom_sede', models.CharField(default='', max_length=30)),
                ('codreg_ips', models.CharField(default='', max_length=30)),
                ('direccion', models.CharField(default='', max_length=200)),
                ('telefono', models.CharField(default='', max_length=120)),
                ('departamento', models.CharField(default='', max_length=120)),
                ('municipio', models.CharField(default='', max_length=120)),
                ('zona', models.CharField(default='', max_length=120)),
                ('sede', models.CharField(default='', max_length=120)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
            options={
                'unique_together': {('codreg_sede', 'nom_sede')},
            },
        ),
        migrations.CreateModel(
            name='Mae_GrupoReportes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_grupo', models.CharField(max_length=120, unique=True)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mae_TiposCampo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mae_SubGrupoReportes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_subgrupo', models.CharField(max_length=120, unique=True)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('mae_gruporeportes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Administracion.mae_gruporeportes')),
            ],
            options={
                'unique_together': {('mae_gruporeportes', 'nom_subgrupo')},
            },
        ),
        migrations.CreateModel(
            name='Mae_Reportes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_reporte', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(default='', max_length=500)),
                ('cuerpo_sql', models.CharField(default='', max_length=5000)),
                ('encabezados', models.CharField(default='', max_length=1000)),
                ('usuario_crea', models.CharField(default='', max_length=20)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now)),
                ('excel', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=1)),
                ('pdf', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=1)),
                ('csv', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=1)),
                ('grilla', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=1)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('mae_gruporeportes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Administracion.mae_gruporeportes')),
                ('mae_subgruporeportes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Administracion.mae_subgruporeportes')),
            ],
        ),
        migrations.CreateModel(
            name='Mae_RepUsuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_usuario', models.CharField(max_length=15)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('cod_sede', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cod_sede', to='Administracion.imhotep_sedesreportes')),
                ('mae_reportes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mae_reportes', to='Administracion.mae_reportes')),
            ],
            options={
                'unique_together': {('cod_sede', 'mae_reportes', 'cod_usuario')},
            },
        ),
        migrations.CreateModel(
            name='Mae_RepParametros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parametro', models.IntegerField()),
                ('parametro_texto', models.CharField(max_length=100)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('mae_reportes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Administracion.mae_reportes')),
                ('mae_tiposcampo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Administracion.mae_tiposcampo')),
            ],
            options={
                'unique_together': {('mae_reportes', 'parametro')},
            },
        ),
    ]
